services:
  backend:
    container_name: backend
    image: thullo
    ports:
      - 5002:5002
    build:
      context: ./backend
      args:
        DB_USER: david
        DB_PASS: test
  frontend:
    container_name: frontend
    image: thullo-frontend
    ports:
      - 3030:3030
    build:
      context: ./frontend/
    depends_on:
      - backend
