FROM debian:buster
RUN apt-get update && apt-get install curl build-essential libssl-dev -y
COPY ./tools/entrypoint.sh /tmp/entrypoint.sh
RUN mkdir /tmp/project
ADD ./client/ /tmp/project/client
WORKDIR /tmp/project/client
RUN chmod +x /tmp/entrypoint.sh
ENTRYPOINT ["/tmp/entrypoint.sh"]
CMD ["npm", "run", "start"]